 export enum ErrorCode {
  // General errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  
  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PAGINATION = 'INVALID_PAGINATION',
  INVALID_QUERY = 'INVALID_QUERY',
  INVALID_FILTER = 'INVALID_FILTER',
  
  // Promotion-specific errors
  PROMOTION_NOT_FOUND = 'PROMOTION_NOT_FOUND',
  PROMOTION_EXPIRED = 'PROMOTION_EXPIRED',
  
  // Favorite-specific errors
  FAVORITE_ALREADY_EXISTS = 'FAVORITE_ALREADY_EXISTS',
  FAVORITE_NOT_FOUND = 'FAVORITE_NOT_FOUND',
  
  // Database errors
  DATABASE_ERROR = 'DATABASE_ERROR',
}


  
